In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb as db

In [11]:
columns_orig = ["FICO", "first_payment_date", "first_time_homebuyer", "maturity_date", "MSA", "MI_perc", "n_units",
           "occupancy_status", "CLTV", "DTI", "UPB", "LTV", "orig_interest_rate", "channel",
           "prepayment_penalty_yn", "amortization_type", "property_state", "property_type", "postal_code",
           "loan_ID", "loan_purpose", "orig_loan_term", "n_borrowers", "seller_name", "super_conforming_flag",
           "pre_harp_loan_sequence_number", "special_eligibility_program", "harp_indicator",
           "property_valuation_method", "interest_only_yn", "vantage_score"]

columns_perf = ["loan_ID", "period", "current_actual_UPB", "current_loan_delinquency_status", "loan_age", "months_to_maturity",
                "underwriting_defect_and_major_servicing_defect_settlement_date", "modification_flag", "zero_balance_code",
                "zero_balance_effective_date", "current_interest_rate", "current_non_interest_bearing_UPB", "DDLPI", "MI_recoveries", "net_sale_proceeds",
                "non_MI_recoveries", "total_expenses", "legal_costs", "maintenance_costs", "tax_and_insurance", "misc_expenses", "actual_loss",
                "cum_modification_costs", "interest_rate_step_indicator", "payment_deferral_flag", "ELTV", "zero_balance_removal_UPB",
                "delinquent_accrued_interest", "delinquency_due_to_disaster", "borrower_assistance_plan", "current_period_modification_costs",
                "current_interest_bearing_UPB", "mortgage_insurance_cancellation", "servicer_name", "bankruptcy_cramdown_costs"]

orig_str = ["MSA", "postal_code", "loan_ID", "pre_harp_loan_sequence_number"]
perf_str = ["loan_ID", "current_loan_delinquency_status", "zero_balance_code", "net_sale_proceeds"]

raw_orig = pd.read_csv("../data/sample_2005/sample_orig_2005.txt", sep="|", names=columns_orig, header=None,
                       dtype=dict.fromkeys(orig_str, str))
raw_perf = pd.read_csv("../data/sample_2005/sample_perf_2005.txt", sep="|", names=columns_perf, header=None,
                       dtype=dict.fromkeys(perf_str, str))

/var/folders/_f/7jxbkdnj68z9vspy512w5bzm0000gn/T/ipykernel_7000/916191745.py:21: DtypeWarning: Columns (7,23,24,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_perf = pd.read_csv("../data/sample_2005/sample_perf_2005.txt", sep="|", names=columns_perf, header=None,

In [17]:
raw_orig.head()

,FICO,first_payment_date,first_time_homebuyer,maturity_date,MSA,MI_perc,n_units,occupancy_status,CLTV,DTI,...,orig_loan_term,n_borrowers,seller_name,super_conforming_flag,pre_harp_loan_sequence_number,special_eligibility_program,harp_indicator,property_valuation_method,interest_only_yn,vantage_score
0,609,200503,N,202002,NaN,12,1,P,90,36,...,180,1,OTHER,N,NaN,NaN,N,7,N,9999
1,646,200505,N,203504,17140,0,1,P,77,43,...,360,2,OTHER,N,NaN,NaN,N,7,N,9999
2,729,200503,N,203502,NaN,0,1,P,61,33,...,360,2,OTHER,N,NaN,NaN,N,7,N,9999
3,748,200503,N,203502,NaN,0,1,P,68,26,...,360,2,OTHER,N,NaN,NaN,N,7,N,9999
4,810,200503,N,203502,43780,0,1,P,49,26,...,360,2,OTHER,N,NaN,NaN,N,7,N,9999

In [18]:
raw_perf.head()

,loan_ID,period,current_actual_UPB,current_loan_delinquency_status,loan_age,months_to_maturity,underwriting_defect_and_major_servicing_defect_settlement_date,modification_flag,zero_balance_code,zero_balance_effective_date,...,ELTV,zero_balance_removal_UPB,delinquent_accrued_interest,delinquency_due_to_disaster,borrower_assistance_plan,current_period_modification_costs,current_interest_bearing_UPB,mortgage_insurance_cancellation,servicer_name,bankruptcy_cramdown_costs
0,F05Q10000006,200502,90000.0,00,0,180,NaN,NaN,NaN,NaN,...,999,NaN,NaN,NaN,NaN,NaN,90000.0,7,U.S. BANK N.A.,NaN
1,F05Q10000006,200503,90000.0,00,1,179,NaN,NaN,NaN,NaN,...,999,NaN,NaN,NaN,NaN,NaN,90000.0,7,U.S. BANK N.A.,NaN
2,F05Q10000006,200504,89000.0,00,2,178,NaN,NaN,NaN,NaN,...,999,NaN,NaN,NaN,NaN,NaN,89000.0,7,U.S. BANK N.A.,NaN
3,F05Q10000006,200505,89000.0,00,3,177,NaN,NaN,NaN,NaN,...,999,NaN,NaN,NaN,NaN,NaN,89000.0,7,U.S. BANK N.A.,NaN
4,F05Q10000006,200506,89000.0,00,4,176,NaN,NaN,NaN,NaN,...,999,NaN,NaN,NaN,NaN,NaN,89000.0,7,U.S. BANK N.A.,NaN